// laon2link Main JavaScript - SHMarket Style
// Category-based navigation without showing all products

// ============================================================================
// Google Analytics Tracking Functions
// ============================================================================

function trackEvent(eventName, params) {
    if (typeof gtag !== 'undefined') {
        gtag('event', eventName, params);
    }
}

function trackProductView(product) {
    trackEvent('view_item', {
        currency: 'EUR',
        value: product.price_eur_markup,
        items: [{
            item_id: product.id,
            item_name: currentLanguage === 'en' ? product.name_en : product.name_kr,
            item_category: product.category_main_en,
            item_category2: product.category_sub_en,
            price: product.price_eur_markup
        }]
    });
}

function trackAddToCart(product, quantity) {
    trackEvent('add_to_cart', {
        currency: 'EUR',
        value: product.price_eur_markup * quantity,
        items: [{
            item_id: product.id,
            item_name: currentLanguage === 'en' ? product.name_en : product.name_kr,
            item_category: product.category_main_en,
            price: product.price_eur_markup,
            quantity: quantity
        }]
    });
}

function trackSearch(searchTerm, resultsCount) {
    trackEvent('search', {
        search_term: searchTerm,
        results_count: resultsCount
    });
}

function trackCategoryView(category, level) {
    trackEvent('view_category', {
        category_name: category,
        category_level: level
    });
}

// ============================================================================
// Global variables
// ============================================================================
let currentProducts = [];
let filteredProducts = [];
let productMap = new Map(); // O(1) lookup by product ID
let currentPage = 1;
let productsPerPage = 12;
let currentView = 'grid';
let currentLanguage = 'en';
let currentCategory = null;
let currentSubCategory = null;
let currentSubSubCategory = null;
let recentlyViewed = [];

// ============================================================================
// URL Parameter Utilities for Individual Product Links
// ============================================================================

function getURLParameter(name) {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get(name);
}

function setURLParameter(name, value) {
    const url = new URL(window.location);
    url.searchParams.set(name, value);
    window.history.pushState({}, '', url);
}

function removeURLParameter(name) {
    const url = new URL(window.location);
    url.searchParams.delete(name);
    window.history.pushState({}, '', url);
}

function clearAllURLParameters() {
    const url = new URL(window.location);
    url.search = '';
    window.history.pushState({}, '', url);
}

function setCategoryURL(category, level, parent = null, grandparent = null) {
    const url = new URL(window.location);
    url.searchParams.set('category', category);
    url.searchParams.set('level', level);

    if (parent) {
        url.searchParams.set('parent', parent);
    } else {
        url.searchParams.delete('parent');
    }

    if (grandparent) {
        url.searchParams.set('grandparent', grandparent);
    } else {
        url.searchParams.delete('grandparent');
    }

    // Remove product parameter when navigating to category
    url.searchParams.delete('product');

    window.history.pushState({}, '', url);
}

// Initialize
document.addEventListener('DOMContentLoaded', function() {
    initializeWebsite();
});

function initializeWebsite() {
    // Load products with validation
    if (typeof productsData === 'undefined' || !Array.isArray(productsData)) {
        console.error('Products data is not loaded or invalid');
        showErrorMessage('Failed to load product catalog. Please refresh the page.');
        return;
    }
    currentProducts = productsData;

    // Build product Map for O(1) lookups (performance optimization)
    productMap = new Map(currentProducts.map(p => [p.id, p]));

    // Validate categories data
    if (typeof categoriesData === 'undefined' || !categoriesData) {
        console.error('Categories data is not loaded or invalid');
        showErrorMessage('Failed to load categories. Please refresh the page.');
        return;
    }

    try {
        // Setup components
        setupCategoryNavigation();
        setupEventListeners();

        // Load saved data
        loadRecentlyViewed();

        // Check if this is a static product page (generated by build script)
        if (typeof window.STATIC_PRODUCT_ID !== 'undefined') {
            // Static product page - show this product
            showProductModal(window.STATIC_PRODUCT_ID, false);
            return; // Exit early - static page handles everything
        }

        // Check if this is a static category page (generated by build script)
        if (typeof window.STATIC_CATEGORY !== 'undefined') {
            // Static category page - show this category
            const level = window.STATIC_CATEGORY_LEVEL || 'main';
            selectCategory(window.STATIC_CATEGORY, level, null, null, false);
            return; // Exit early - static page handles everything
        }

        // Check URL parameters for navigation state (for URL-based routing on main site)
        const productIdFromURL = getURLParameter('product');
        const categoryFromURL = getURLParameter('category');
        const levelFromURL = getURLParameter('level');
        const parentFromURL = getURLParameter('parent');
        const grandparentFromURL = getURLParameter('grandparent');

        if (productIdFromURL) {
            // If product ID in URL parameter, open that product modal
            showProductModal(productIdFromURL, false);
        } else if (categoryFromURL && levelFromURL) {
            // If category in URL parameter, select that category
            selectCategory(categoryFromURL, levelFromURL, parentFromURL, grandparentFromURL, false);
        } else {
            // Show welcome message initially (no products, no category)
            showWelcomeMessage();
        }

        // Setup back to top button
        setupBackToTop();

        console.log('Website initialized successfully');
    } catch (error) {
        console.error('Error initializing website:', error);
        showErrorMessage('An error occurred while loading the website. Please refresh the page.');
    }
}

// Show error message to user
function showErrorMessage(message) {
    const mainContent = document.querySelector('.product-area');
    if (mainContent) {
        // Create elements safely to prevent XSS
        const errorDiv = document.createElement('div');
        errorDiv.style.cssText = 'text-align: center; padding: 40px; background: #fee; border: 1px solid #fcc; border-radius: 8px; margin: 20px;';

        const icon = document.createElement('i');
        icon.className = 'fas fa-exclamation-triangle';
        icon.style.cssText = 'font-size: 48px; color: #c33; margin-bottom: 16px;';

        const heading = document.createElement('h3');
        heading.style.cssText = 'color: #c33; margin-bottom: 12px;';
        heading.textContent = 'Error Loading Page';

        const paragraph = document.createElement('p');
        paragraph.style.cssText = 'color: #666;';
        paragraph.textContent = message; // Safe: uses textContent instead of innerHTML

        const button = document.createElement('button');
        button.style.cssText = 'margin-top: 16px; padding: 10px 20px; background: #0066cc; color: white; border: none; border-radius: 4px; cursor: pointer;';
        button.innerHTML = '<i class="fas fa-sync"></i> Refresh Page';
        button.addEventListener('click', () => location.reload());

        errorDiv.appendChild(icon);
        errorDiv.appendChild(heading);
        errorDiv.appendChild(paragraph);
        errorDiv.appendChild(button);

        mainContent.innerHTML = '';
        mainContent.appendChild(errorDiv);
    }
}

// Category Navigation Setup
function setupCategoryNavigation() {
    // Build main navigation
    buildMainNavigation();
    
    // Build category tree in sidebar
    buildCategoryTree();
    
    // Build category dropdown
    buildCategoryDropdown();
    
    // Build footer categories
    buildFooterCategories();
    
    // Build category cards on welcome page
    buildCategoryCards();
}

function buildMainNavigation() {
    const mainNavLinks = document.getElementById('mainNavLinks');
    let navHTML = '';
    
    // Add main category links (limit to first 5)
    let count = 0;
    for (const [catName, catData] of Object.entries(categoriesData)) {
        if (count >= 5) break;
        navHTML += `<a href="#" data-category="${catName}" data-level="main">${catData.name_en}</a>`;
        count++;
    }
    
    mainNavLinks.innerHTML = navHTML;
}

function buildCategoryTree() {
    const categoryTree = document.getElementById('categoryTree');
    let treeHTML = '';
    
    for (const [mainCat, mainData] of Object.entries(categoriesData)) {
        treeHTML += `
            <div class="category-item">
                <a href="#" class="category-link ${Object.keys(mainData.subcategories || {}).length > 0 ? 'has-children' : ''}" 
                   data-category="${mainCat}" data-level="main">
                    ${mainData.name_en}
                </a>
        `;
        
        if (mainData.subcategories && Object.keys(mainData.subcategories).length > 0) {
            treeHTML += '<div class="subcategories">';
            
            for (const [subCat, subData] of Object.entries(mainData.subcategories)) {
                treeHTML += `
                    <div class="category-item">
                        <a href="#" class="category-link subcategory-link ${Object.keys(subData.subcategories || {}).length > 0 ? 'has-children' : ''}" 
                           data-category="${subCat}" data-level="sub" data-parent="${mainCat}">
                            ${subData.name_en}
                        </a>
                `;
                
                if (subData.subcategories && Object.keys(subData.subcategories).length > 0) {
                    treeHTML += '<div class="subcategories">';
                    
                    for (const [subSubCat, subSubData] of Object.entries(subData.subcategories)) {
                        treeHTML += `
                            <div class="category-item">
                                <a href="#" class="category-link subsubcategory-link" 
                                   data-category="${subSubCat}" data-level="subsub" 
                                   data-parent="${subCat}" data-grandparent="${mainCat}">
                                    ${subSubData.name_en}
                                </a>
                            </div>
                        `;
                    }
                    
                    treeHTML += '</div>';
                }
                
                treeHTML += '</div>';
            }
            
            treeHTML += '</div>';
        }
        
        treeHTML += '</div>';
    }
    
    categoryTree.innerHTML = treeHTML;
}

function buildCategoryDropdown() {
    const categoriesGrid = document.getElementById('categoriesGrid');
    let gridHTML = '';
    
    for (const [mainCat, mainData] of Object.entries(categoriesData)) {
        gridHTML += `
            <div class="dropdown-category">
                <h4><a href="#" data-category="${mainCat}" data-level="main">${mainData.name_en}</a></h4>
                <ul>
        `;
        
        if (mainData.subcategories) {
            let subCount = 0;
            for (const [subCat, subData] of Object.entries(mainData.subcategories)) {
                if (subCount >= 5) break; // Limit subcategories shown
                gridHTML += `
                    <li><a href="#" data-category="${subCat}" data-level="sub" data-parent="${mainCat}">
                        ${subData.name_en}
                    </a></li>
                `;
                subCount++;
            }
        }
        
        gridHTML += '</ul></div>';
    }
    
    categoriesGrid.innerHTML = gridHTML;
}

function buildFooterCategories() {
    const footerCategories = document.getElementById('footerCategories');
    let footerHTML = '';
    
    let count = 0;
    for (const [catName, catData] of Object.entries(categoriesData)) {
        if (count >= 5) break;
        footerHTML += `<li><a href="#" data-category="${catName}" data-level="main">${catData.name_en}</a></li>`;
        count++;
    }
    
    footerCategories.innerHTML = footerHTML;
}

function buildCategoryCards() {
    const categoryCards = document.getElementById('categoryCards');
    let cardsHTML = '';

    // Create cards for main categories
    for (const [catName, catData] of Object.entries(categoriesData)) {
        const categoryProducts = currentProducts.filter(p => p.category_main_en === catName);
        const productCount = categoryProducts.length;

        // Get the first product's image for this category
        let imageUrl = '/images/no-image.png';
        if (categoryProducts.length > 0 && categoryProducts[0].images && categoryProducts[0].images.length > 0) {
            imageUrl = `images/products/${categoryProducts[0].images[0]}`;
        }

        cardsHTML += `
            <div class="category-card" data-category="${catName}" data-level="main">
                <div class="category-card-image">
                    <img src="${imageUrl}" alt="${catData.name_en}"
                         onerror="this.src='/images/no-image.png'">
                </div>
                <h4>${catData.name_en}</h4>
                <span>${productCount} products</span>
            </div>
        `;
    }

    categoryCards.innerHTML = cardsHTML;

    // Add click handlers
    document.querySelectorAll('.category-card').forEach(card => {
        card.addEventListener('click', function(e) {
            e.preventDefault(); // Prevent default link behavior
            e.stopPropagation(); // Prevent generic handler from interfering
            e.stopImmediatePropagation(); // Prevent other handlers on same element
            selectCategory(this.dataset.category, 'main');
        });
    });
}

function getCategoryIcon(category) {
    const icons = {
        'PLC': 'fa-microchip',
        'Servo motor/servo driver': 'fa-cogs',
        'Stepping motor/driver/BLDC': 'fa-gear',
        'HMI': 'fa-desktop',
        'INVERTER': 'fa-bolt',
        'SENSOR': 'fa-radar'
    };
    return icons[category] || 'fa-cube';
}

// Event Listeners
function setupEventListeners() {
    // Home link
    const homeLink = document.querySelector('.home-link');
    if (homeLink) {
        homeLink.addEventListener('click', function(e) {
            e.preventDefault();
            resetToHome();
        });
    }

    // Company logo link
    const companyLogoLink = document.querySelector('.company-logo-link');
    if (companyLogoLink) {
        companyLogoLink.addEventListener('click', function(e) {
            e.preventDefault();
            resetToHome();
        });
    }

    // All categories button
    const allCategoriesBtn = document.getElementById('allCategoriesBtn');
    if (allCategoriesBtn) {
        allCategoriesBtn.addEventListener('click', function() {
            const dropdown = document.getElementById('categoriesDropdown');
            if (dropdown) {
                dropdown.classList.toggle('show');
            }
        });
    }

    // Close dropdown when clicking outside
    document.addEventListener('click', function(e) {
        if (!e.target.closest('.category-nav')) {
            const dropdown = document.getElementById('categoriesDropdown');
            if (dropdown) {
                dropdown.classList.remove('show');
            }
        }
    });
    
    // Category links
    document.addEventListener('click', function(e) {
        if (e.target.dataset.category) {
            e.preventDefault();

            // Skip if this is a category with children - handled by specific listener below
            if (e.target.classList.contains('has-children')) {
                return;
            }

            const category = e.target.dataset.category;
            const level = e.target.dataset.level;
            const parent = e.target.dataset.parent;
            const grandparent = e.target.dataset.grandparent;

            selectCategory(category, level, parent, grandparent);

            // Close dropdown if open
            document.getElementById('categoriesDropdown').classList.remove('show');
        }
    });
    
    // Search
    const searchBtn = document.getElementById('searchBtn');
    const searchInput = document.getElementById('searchInput');

    if (searchBtn) {
        searchBtn.addEventListener('click', performSearch);
    }

    if (searchInput) {
        // Prevent autofill - clear any autofilled values
        searchInput.value = '';

        // Additional clearing after a short delay to catch late autofill
        setTimeout(function() {
            if (searchInput && searchInput.value && !searchInput.value.trim()) {
                searchInput.value = '';
            }
        }, 100);

        // Also clear on page load if it contains an email pattern
        setTimeout(function() {
            if (searchInput && searchInput.value && searchInput.value.includes('@')) {
                searchInput.value = '';
            }
        }, 500);

        searchInput.addEventListener('keypress', function(e) {
            if (e.key === 'Enter') performSearch();
        });
    }

    // Quick search tags
    document.querySelectorAll('.search-tag').forEach(tag => {
        tag.addEventListener('click', function(e) {
            e.preventDefault();
            if (searchInput) {
                searchInput.value = this.dataset.search;
                performSearch();
            }
        });
    });

    // View mode
    document.querySelectorAll('.view-btn').forEach(btn => {
        btn.addEventListener('click', function() {
            document.querySelectorAll('.view-btn').forEach(b => b.classList.remove('active'));
            this.classList.add('active');
            currentView = this.dataset.view;
            displayProducts();
        });
    });

    // Sort
    const sortSelect = document.getElementById('sortSelect');
    if (sortSelect) {
        sortSelect.addEventListener('change', function() {
            sortProducts(this.value);
        });
    }

    // Items per page
    const itemsPerPage = document.getElementById('itemsPerPage');
    if (itemsPerPage) {
        itemsPerPage.addEventListener('change', function() {
            productsPerPage = parseInt(this.value);
            currentPage = 1;
            displayProducts();
        });
    }

    // Price filter
    const applyPriceFilter = document.getElementById('applyPriceFilter');
    if (applyPriceFilter) {
        applyPriceFilter.addEventListener('click', applyFilters);
    }

    // Clear filters
    const clearFiltersBtn = document.getElementById('clearFilters');
    if (clearFiltersBtn) {
        clearFiltersBtn.addEventListener('click', clearFilters);
    }

    // Category panel collapse
    const categoryPanelTitle = document.getElementById('categoryPanelTitle');
    if (categoryPanelTitle) {
        categoryPanelTitle.addEventListener('click', function() {
            const categoryTree = document.getElementById('categoryTree');
            const collapseIcon = this.querySelector('.collapse-icon');

            if (categoryTree && collapseIcon) {
                categoryTree.classList.toggle('collapsed');

                // Toggle icon rotation
                if (categoryTree.classList.contains('collapsed')) {
                    collapseIcon.style.transform = 'rotate(-90deg)';
                } else {
                    collapseIcon.style.transform = 'rotate(0deg)';
                }
            }
        });
    }

    // Modal close - using event delegation for all modals
    document.addEventListener('click', function(e) {
        if (e.target.classList.contains('close-modal')) {
            if (e.target.closest('#productModal')) {
                closeModal();
            } else if (e.target.closest('#authModal')) {
                closeAuthModal();
            }
        }

        // Close modal when clicking on backdrop
        if (e.target.id === 'productModal') {
            closeModal();
        }
    });
    
    // Category tree expand/collapse
    document.querySelectorAll('.category-link.has-children').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            e.stopPropagation(); // Prevent generic category listener from firing

            if (e.target === this) {
                // Toggle subcategories dropdown
                const subcategories = this.nextElementSibling;
                if (subcategories && subcategories.classList.contains('subcategories')) {
                    subcategories.classList.toggle('show');
                    this.classList.toggle('expanded');
                }

                // ALSO select this category to show products
                const category = this.dataset.category;
                const level = this.dataset.level;
                const parent = this.dataset.parent;
                const grandparent = this.dataset.grandparent;

                if (category) {
                    selectCategory(category, level, parent, grandparent);
                }

                // Close dropdown if open
                document.getElementById('categoriesDropdown').classList.remove('show');
            }
        });
    });

    // Handle browser back/forward navigation
    window.addEventListener('popstate', function() {
        const productIdFromURL = getURLParameter('product');
        const categoryFromURL = getURLParameter('category');
        const levelFromURL = getURLParameter('level');
        const parentFromURL = getURLParameter('parent');
        const grandparentFromURL = getURLParameter('grandparent');
        const productModal = document.getElementById('productModal');

        if (productIdFromURL) {
            // If URL has product ID, open that product modal (don't update URL)
            showProductModal(productIdFromURL, false);
        } else if (categoryFromURL && levelFromURL) {
            // If URL has category, select that category (don't update URL)
            if (productModal && productModal.style.display === 'block') {
                productModal.style.display = 'none';
            }
            selectCategory(categoryFromURL, levelFromURL, parentFromURL, grandparentFromURL, false);
        } else {
            // No category or product - return to home
            if (productModal && productModal.style.display === 'block') {
                productModal.style.display = 'none';
            }
            // Reset to home state without updating URL (it's already at home)
            currentCategory = null;
            currentSubCategory = null;
            currentSubSubCategory = null;
            filteredProducts = [];
            currentPage = 1;

            // Clear active category highlights
            document.querySelectorAll('.category-link').forEach(link => {
                link.classList.remove('active');
            });

            // Reset breadcrumb
            updateBreadcrumb();

            // Show welcome message
            showWelcomeMessage();
        }
    });
}

// Category Selection
function selectCategory(category, level, parent = null, grandparent = null, updateURL = true) {
    // Validate inputs
    if (!category || !level) {
        console.error('Invalid category selection:', { category, level });
        return;
    }

    // Close any open product modal to prevent automatic product display
    const productModal = document.getElementById('productModal');
    if (productModal && productModal.style.display === 'block') {
        closeModal();
    }

    // Update current category
    if (level === 'main') {
        currentCategory = category;
        currentSubCategory = null;
        currentSubSubCategory = null;
    } else if (level === 'sub') {
        currentCategory = parent;
        currentSubCategory = category;
        currentSubSubCategory = null;
    } else if (level === 'subsub') {
        currentCategory = grandparent;
        currentSubCategory = parent;
        currentSubSubCategory = category;
    } else {
        console.error('Invalid category level:', level);
        return;
    }

    // Update URL with category parameters for shareable links
    if (updateURL) {
        setCategoryURL(category, level, parent, grandparent);
    }

    // Filter products
    filteredProducts = currentProducts.filter(product => {
        if (level === 'main') {
            return product.category_main_en === category;
        } else if (level === 'sub') {
            return product.category_sub_en === category;
        } else if (level === 'subsub') {
            return product.category_subsub_en === category;
        }
        return false;
    });

    // Track category view in Google Analytics
    trackCategoryView(category, level);

    // Update UI
    updateBreadcrumb();
    highlightActiveCategory(category);
    hideWelcomeMessage();
    currentPage = 1;
    displayProducts();

    // Scroll to category navigation bar when selecting a category
    const categoryNav = document.querySelector('.category-nav');
    if (categoryNav) {
        categoryNav.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
}

// Update breadcrumb
function updateBreadcrumb() {
    const breadcrumbTrail = document.getElementById('breadcrumbTrail');
    if (!breadcrumbTrail) {
        console.warn('Breadcrumb element not found');
        return;
    }

    let trail = '';

    if (currentCategory) {
        trail = `<a href="#" data-category="${currentCategory}" data-level="main">${currentCategory}</a>`;

        if (currentSubCategory) {
            trail += ` <span class="separator">></span> `;
            trail += `<a href="#" data-category="${currentSubCategory}" data-level="sub" data-parent="${currentCategory}">${currentSubCategory}</a>`;

            if (currentSubSubCategory) {
                trail += ` <span class="separator">></span> `;
                trail += `<span>${currentSubSubCategory}</span>`;
            }
        }
    } else {
        trail = 'Select a Category';
    }

    breadcrumbTrail.innerHTML = trail;
}

// Highlight active category
function highlightActiveCategory(category) {
    // Remove all active classes
    document.querySelectorAll('.category-link').forEach(link => {
        link.classList.remove('active');
    });
    
    // Add active class to selected
    document.querySelectorAll(`.category-link[data-category="${category}"]`).forEach(link => {
        link.classList.add('active');
    });
}

// Show/Hide welcome message
function showWelcomeMessage() {
    const welcomeMessage = document.getElementById('welcomeMessage');
    const productsContainer = document.getElementById('productsContainer');
    const pagination = document.getElementById('pagination');
    const resultsCount = document.getElementById('resultsCount');

    if (welcomeMessage) welcomeMessage.style.display = 'block';
    if (productsContainer) productsContainer.style.display = 'none';
    if (pagination) pagination.style.display = 'none';
    if (resultsCount) resultsCount.textContent = '0';
}

function hideWelcomeMessage() {
    const welcomeMessage = document.getElementById('welcomeMessage');
    const productsContainer = document.getElementById('productsContainer');

    if (welcomeMessage) welcomeMessage.style.display = 'none';
    if (productsContainer) productsContainer.style.display = 'block';
}

// Reset to home state
function resetToHome() {
    // Reset all category state
    currentCategory = null;
    currentSubCategory = null;
    currentSubSubCategory = null;
    filteredProducts = [];
    currentPage = 1;

    // Clear all URL parameters (category, product, etc.)
    clearAllURLParameters();

    // Clear active category highlights
    document.querySelectorAll('.category-link').forEach(link => {
        link.classList.remove('active');
    });

    // Reset breadcrumb
    updateBreadcrumb();

    // Show welcome message
    showWelcomeMessage();

    // Scroll to category navigation bar
    const categoryNav = document.querySelector('.category-nav');
    if (categoryNav) {
        categoryNav.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
}

// Search
function performSearch() {
    const searchInput = document.getElementById('searchInput');
    if (!searchInput) {
        console.error('Search input not found');
        return;
    }

    const searchTerm = searchInput.value.toLowerCase().trim();

    if (!searchTerm) {
        showWelcomeMessage();
        return;
    }

    filteredProducts = currentProducts.filter(product => {
        const searchableText = [
            product.name_en || '',
            product.name_kr || '',
            product.model_number || '',
            product.manufacturer || '',
            product.category_main_en || '',
            product.category_sub_en || ''
        ].join(' ').toLowerCase();

        return searchableText.includes(searchTerm);
    });

    // Track search in Google Analytics
    trackSearch(searchTerm, filteredProducts.length);

    // Update breadcrumb for search
    const breadcrumbTrail = document.getElementById('breadcrumbTrail');
    if (breadcrumbTrail) {
        breadcrumbTrail.innerHTML = `Search results for "${searchTerm}"`;
    }

    hideWelcomeMessage();
    currentPage = 1;
    displayProducts();
}

// Apply filters
function applyFilters() {
    const minPriceInput = document.getElementById('minPrice');
    const maxPriceInput = document.getElementById('maxPrice');

    const minPrice = parseFloat(minPriceInput?.value) || 0;
    const maxPrice = parseFloat(maxPriceInput?.value) || Infinity;

    // Validate price range
    if (maxPrice !== Infinity && minPrice > maxPrice) {
        showNotification('Minimum price cannot be greater than maximum price');
        if (minPriceInput) minPriceInput.style.borderColor = '#ff0000';
        if (maxPriceInput) maxPriceInput.style.borderColor = '#ff0000';
        setTimeout(() => {
            if (minPriceInput) minPriceInput.style.borderColor = '';
            if (maxPriceInput) maxPriceInput.style.borderColor = '';
        }, 2000);
        return;
    }

    if (minPrice < 0 || (maxPrice !== Infinity && maxPrice < 0)) {
        showNotification('Price values cannot be negative');
        return;
    }

    const checkedConditions = Array.from(document.querySelectorAll('input[name="condition"]:checked'))
        .map(cb => cb.value);
    
    // Start with current category products or all
    let baseProducts = [];
    if (currentCategory) {
        baseProducts = currentProducts.filter(product => {
            if (currentSubSubCategory) {
                return product.category_subsub_en === currentSubSubCategory;
            } else if (currentSubCategory) {
                return product.category_sub_en === currentSubCategory;
            } else {
                return product.category_main_en === currentCategory;
            }
        });
    } else {
        baseProducts = [...currentProducts];
    }
    
    // Apply filters
    filteredProducts = baseProducts.filter(product => {
        // Price filter
        if (product.price_eur_markup < minPrice || product.price_eur_markup > maxPrice) {
            return false;
        }

        // Condition filter
        if (checkedConditions.length > 0) {
            // Extract condition from product name or specifications
            const productCondition = getProductCondition(product);
            if (!checkedConditions.includes(productCondition)) {
                return false;
            }
        }

        return true;
    });
    
    currentPage = 1;
    displayProducts();
}

// Helper function to get product condition
function getProductCondition(product) {
    // Check product name for condition keywords
    const name = (product.name_en || product.name_kr || '').toLowerCase();

    if (name.includes('[used]') || name.includes('[중고]') || name.includes('used')) {
        return 'used';
    }

    if (name.includes('[new]') || name.includes('[신품]') || name.includes('new')) {
        return 'new';
    }

    if (name.includes('refurbished') || name.includes('재생')) {
        return 'refurbished';
    }

    // Check specifications
    if (product.specifications) {
        try {
            const specs = JSON.parse(product.specifications);
            const condition = (specs.Condition || specs.condition || '').toLowerCase();
            if (condition.includes('new')) return 'new';
            if (condition.includes('refurbished')) return 'refurbished';
        } catch (e) {
            // Ignore parse errors
        }
    }

    // Default to 'used' since most products in catalog are used
    return 'used';
}

// Clear filters
function clearFilters() {
    const minPrice = document.getElementById('minPrice');
    const maxPrice = document.getElementById('maxPrice');

    if (minPrice) minPrice.value = '';
    if (maxPrice) maxPrice.value = '';

    // Clear all checkboxes except "used" condition (which is default)
    document.querySelectorAll('input[type="checkbox"]').forEach(cb => {
        const isUsedConditionCheckbox = cb.name === 'condition' && cb.value === 'used';
        if (!isUsedConditionCheckbox) {
            cb.checked = false;
        } else {
            cb.checked = true; // Ensure "used" is checked
        }
    });

    // Re-apply category filter only (preserve current level)
    if (currentSubSubCategory) {
        selectCategory(currentSubSubCategory, 'subsub', currentSubCategory, currentCategory);
    } else if (currentSubCategory) {
        selectCategory(currentSubCategory, 'sub', currentCategory);
    } else if (currentCategory) {
        selectCategory(currentCategory, 'main');
    } else {
        // If no category selected, show welcome message
        showWelcomeMessage();
    }

    showNotification('Filters cleared');
}

// Sort products
function sortProducts(sortBy) {
    switch(sortBy) {
        case 'name-asc':
            filteredProducts.sort((a, b) => (a.name_en || '').localeCompare(b.name_en || ''));
            break;
        case 'name-desc':
            filteredProducts.sort((a, b) => (b.name_en || '').localeCompare(a.name_en || ''));
            break;
        case 'price-asc':
            filteredProducts.sort((a, b) => a.price_eur_markup - b.price_eur_markup);
            break;
        case 'price-desc':
            filteredProducts.sort((a, b) => b.price_eur_markup - a.price_eur_markup);
            break;
        case 'newest':
            filteredProducts.sort((a, b) => new Date(b.scraped_at) - new Date(a.scraped_at));
            break;
    }
    
    displayProducts();
}

// Image loading failsafe - set timeout for slow/hanging images
function setupImageLoadTimeout(img, timeout = 5000) {
    const timer = setTimeout(() => {
        if (!img.complete || img.naturalWidth === 0) {
            // Image hasn't loaded after timeout - force placeholder
            if (!img.dataset.failed) {
                img.dataset.failed = '1';
                img.onerror = null;
                img.src = '/images/no-image.png';
                img.style.opacity = '1';
            }
        }
    }, timeout);

    // Clear timeout if image loads successfully
    img.addEventListener('load', () => clearTimeout(timer), { once: true });
    img.addEventListener('error', () => clearTimeout(timer), { once: true });
}

// Display products
function displayProducts() {
    const productsGrid = document.getElementById('productsGrid');
    const resultsCount = document.getElementById('resultsCount');

    if (!productsGrid) {
        console.error('Products grid element not found');
        return;
    }

    // Update count
    if (resultsCount) {
        resultsCount.textContent = filteredProducts.length;
    }
    
    // Calculate pagination
    const startIndex = (currentPage - 1) * productsPerPage;
    const endIndex = startIndex + productsPerPage;
    const pageProducts = filteredProducts.slice(startIndex, endIndex);
    
    // Set view class
    productsGrid.className = currentView === 'list' ? 'products-list' : 'products-grid';
    
    // Generate HTML
    let html = '';
    pageProducts.forEach(product => {
        html += createProductCard(product);
    });
    
    productsGrid.innerHTML = html || '<p style="text-align: center; padding: 40px;">No products found in this category.</p>';
    
    // Add event listeners to product cards
    setupProductCardEvents();
    
    // Update pagination
    updatePagination();

    // Show/hide pagination
    const pagination = document.getElementById('pagination');
    if (pagination) {
        pagination.style.display = filteredProducts.length > productsPerPage ? 'flex' : 'none';
    }
}

// Create product card
function createProductCard(product) {
    if (!product) {
        console.warn('Invalid product data');
        return '';
    }

    const name = currentLanguage === 'kr' && product.name_kr ? product.name_kr : (product.name_en || 'Unknown Product');
    const imageUrl = product.images && product.images[0]
        ? `images/products/${product.images[0]}`
        : '/images/no-image.png';

    const isNew = false; // You can add logic to determine if product is new

    return `
        <div class="product-card" data-product-id="${product.id}">
            <div class="product-image-wrapper">
                <img src="${imageUrl}" alt="${name}" class="product-image loaded" loading="lazy"
                     onerror="if(!this.dataset.failed){this.dataset.failed='1';this.style.transition='none';this.onerror=null;this.src='/images/no-image.png';this.style.opacity='1';}"
                     onload="this.style.opacity='1';">
                ${isNew ? '<span class="product-badge">NEW</span>' : ''}
            </div>
            <div class="product-info">
                <div class="product-category">${product.category_sub_en || product.category_main_en || ''}</div>
                <div class="product-name" title="${name}">${name}</div>
                <div class="product-price">
                    ${product.price_eur_markup > 0 ? `€${product.price_eur_markup.toFixed(2)}` : 'Contact for Price'}
                </div>
                <div class="product-actions">
                    <button class="btn-details" data-action="view-details" data-product-id="${product.id}">
                        <i class="fas fa-eye"></i> View Details
                    </button>
                    <button class="btn-cart" data-action="contact" data-product-id="${product.id}">
                        <i class="fas fa-envelope"></i> Inquire
                    </button>
                </div>
            </div>
        </div>
    `;
}

// Setup product card events using event delegation (performance optimization)
function setupProductCardEvents() {
    const productsGrid = document.getElementById('productsGrid');
    if (!productsGrid) return;

    // Remove old listeners if they exist
    if (productsGrid._clickHandler) {
        productsGrid.removeEventListener('click', productsGrid._clickHandler);
    }
    if (productsGrid._errorHandler) {
        productsGrid.removeEventListener('error', productsGrid._errorHandler, true);
    }
    if (productsGrid._loadHandler) {
        productsGrid.removeEventListener('load', productsGrid._loadHandler, true);
    }

    // Click event handler for product interactions
    const clickHandler = function(e) {
        // Handle button clicks
        const button = e.target.closest('button[data-action]');
        if (button) {
            e.preventDefault();
            e.stopPropagation();
            const action = button.dataset.action;
            const productId = button.dataset.productId;

            if (action === 'view-details') {
                showProductModal(productId);
            } else if (action === 'contact') {
                contactForProduct(productId);
            }
            return;
        }

        // Handle card clicks (excluding buttons) - ONLY for click events
        const card = e.target.closest('.product-card');
        if (card && !e.target.closest('button')) {
            showProductModal(card.dataset.productId);
        }
    };

    // Separate handler for image errors
    const errorHandler = function(e) {
        if (e.target.tagName === 'IMG' && e.target.classList.contains('product-image')) {
            // Prevent further error events
            e.target.onerror = null;
            // Set fallback image
            e.target.src = e.target.dataset.fallback || '/images/no-image.png';
            // Make visible immediately to prevent flickering
            e.target.classList.add('loaded');
        }
    };

    // Separate handler for image loads
    const loadHandler = function(e) {
        if (e.target.tagName === 'IMG' && e.target.classList.contains('product-image')) {
            e.target.classList.add('loaded');
            // Set up timeout failsafe for images that may hang
            setupImageLoadTimeout(e.target);
        }
    };

    // Add event listeners
    productsGrid.addEventListener('click', clickHandler);
    productsGrid.addEventListener('error', errorHandler, true); // Capture phase for img errors
    productsGrid.addEventListener('load', loadHandler, true);  // Capture phase for img loads

    // Also set up timeouts for any images already in the DOM
    productsGrid.querySelectorAll('img.product-image').forEach(img => {
        if (!img.complete || img.naturalWidth === 0) {
            setupImageLoadTimeout(img);
        }
    });

    // Store references for cleanup
    productsGrid._clickHandler = clickHandler;
    productsGrid._errorHandler = errorHandler;
    productsGrid._loadHandler = loadHandler;
}

// Show product modal
function showProductModal(productId, updateURL = true) {
    // Use Map for O(1) lookup instead of O(n) find()
    const product = productMap.get(productId);
    if (!product) {
        console.error('Product not found:', productId);
        showNotification('Product not found');
        return;
    }

    // Update URL with product ID for shareable link (unless called from popstate)
    if (updateURL) {
        setURLParameter('product', productId);
    }

    // Track product view in Google Analytics
    trackProductView(product);

    // Add to recently viewed
    addToRecentlyViewed(product);

    const modalTitle = document.getElementById('modalProductTitle');
    const modalContent = document.getElementById('modalContent');
    const productModal = document.getElementById('productModal');

    if (!modalTitle || !modalContent || !productModal) {
        console.error('Modal elements not found');
        showNotification('Unable to display product details');
        return;
    }

    const name = currentLanguage === 'kr' && product.name_kr ? product.name_kr : (product.name_en || 'Unknown Product');
    
    modalTitle.textContent = name;
    
    // Generate modal content
    let imagesHTML = '';
    if (product.images && product.images.length > 0) {
        const mainImage = product.images[0];
        imagesHTML = `
            <div class="product-images-section">
                <img src="images/products/${mainImage}" alt="${name}"
                     class="main-product-image" id="mainProductImage"
                     onerror="if(!this.dataset.failed){this.dataset.failed='1';this.style.transition='none';this.onerror=null;this.src='/images/no-image.png';this.style.opacity='1';}"
                     onload="this.style.opacity='1';">
                ${product.images.length > 1 ? `
                    <div class="image-thumbnails" data-thumbnail-container>
                        ${product.images.map((img, idx) => `
                            <img src="images/products/${img}" alt="${name}" loading="lazy"
                                 class="thumbnail ${idx === 0 ? 'active' : ''}"
                                 data-image="${img}"
                                 onerror="if(!this.dataset.failed){this.dataset.failed='1';this.style.transition='none';this.onerror=null;this.src='/images/no-image.png';this.style.opacity='1';}"
                                 onload="this.style.opacity='1';">
                        `).join('')}
                    </div>
                ` : ''}
            </div>
        `;
    } else {
        // Show placeholder if no images
        imagesHTML = `
            <div class="product-images-section">
                <img src="/images/no-image.png" alt="${name}"
                     class="main-product-image"
                     onload="this.style.opacity=1;">
            </div>
        `;
    }
    
    // Parse specifications
    let specsHTML = '';
    if (product.specifications) {
        try {
            const specs = JSON.parse(product.specifications);

            // Filter out empty or meaningless specs (where both key and value are just "-")
            const validSpecs = Object.entries(specs).filter(([key, value]) => {
                const k = key.trim();
                const v = String(value).trim();
                // Skip if key is "-" or empty, or if value is "-", "N/A", or empty
                return k !== '-' && k !== '' && v !== '-' && v !== '' && v !== 'N/A';
            });

            if (validSpecs.length > 0) {
                specsHTML = `
                    <div class="specifications-section">
                        <h4>Specifications</h4>
                        <table class="specs-table">
                            ${validSpecs.map(([key, value]) => `
                                <tr>
                                    <th>${key}</th>
                                    <td>${value}</td>
                                </tr>
                            `).join('')}
                        </table>
                    </div>
                `;
            }
        } catch (e) {
            console.error('Error parsing specifications:', e);
        }
    }
    
    modalContent.innerHTML = `
        <div class="product-modal-grid">
            ${imagesHTML}
            <div class="product-details-section">
                <h3>${name}</h3>
                <div class="product-meta">
                    <div class="meta-row">
                        <span class="meta-label">Product ID:</span>
                        <span class="meta-value">${product.id}</span>
                    </div>
                    <div class="meta-row">
                        <span class="meta-label">Category:</span>
                        <span class="meta-value">${product.category_main_en || 'N/A'}</span>
                    </div>
                </div>
                <div class="modal-price">
                    ${product.price_eur_markup > 0 ? `€${product.price_eur_markup.toFixed(2)}` : 'Contact for Price'}
                </div>
                <div class="modal-actions">
                    <button class="btn-primary" data-action="contact" data-product-id="${product.id}">
                        <i class="fas fa-envelope"></i> Request Quote
                    </button>
                </div>
                ${specsHTML}
            </div>
        </div>
    `;

    // Add event delegation for modal content
    setupModalEventDelegation();

    // Show modal
    document.getElementById('productModal').style.display = 'block';
}

// Setup modal event delegation
function setupModalEventDelegation() {
    const modalContent = document.getElementById('modalContent');
    if (!modalContent) return;

    // Remove old listeners if they exist
    if (modalContent._clickHandler) {
        modalContent.removeEventListener('click', modalContent._clickHandler);
    }
    if (modalContent._errorHandler) {
        modalContent.removeEventListener('error', modalContent._errorHandler, true);
    }
    if (modalContent._loadHandler) {
        modalContent.removeEventListener('load', modalContent._loadHandler, true);
    }

    // Click event handler
    const clickHandler = function(e) {
        // Handle thumbnail clicks
        if (e.target.classList.contains('thumbnail')) {
            const img = e.target.dataset.image;
            if (img) {
                const mainImage = document.getElementById('mainProductImage');
                if (mainImage) {
                    mainImage.src = `images/products/${img}`;
                }
                // Update active state
                document.querySelectorAll('.thumbnail').forEach(thumb => {
                    thumb.classList.remove('active');
                });
                e.target.classList.add('active');
            }
            return;
        }

        // Handle contact button
        const button = e.target.closest('button[data-action="contact"]');
        if (button) {
            e.preventDefault();
            const productId = button.dataset.productId;
            if (productId) {
                contactForProduct(productId);
            }
            return;
        }
    };

    // Separate handler for image errors
    const errorHandler = function(e) {
        if (e.target.tagName === 'IMG' && e.target.dataset.fallback) {
            // Prevent further error events
            e.target.onerror = null;
            // Set fallback image
            e.target.src = e.target.dataset.fallback;
            // Make visible immediately
            e.target.style.opacity = 1;
        }
    };

    // Separate handler for image loads
    const loadHandler = function(e) {
        if (e.target.tagName === 'IMG') {
            e.target.style.opacity = 1;
            // Set up timeout failsafe for modal images
            setupImageLoadTimeout(e.target);
        }
    };

    // Add event listeners
    modalContent.addEventListener('click', clickHandler);
    modalContent.addEventListener('error', errorHandler, true); // Capture phase
    modalContent.addEventListener('load', loadHandler, true);  // Capture phase

    // Set up timeouts for any images already in the modal
    modalContent.querySelectorAll('img').forEach(img => {
        if (!img.complete || img.naturalWidth === 0) {
            setupImageLoadTimeout(img);
        }
    });

    // Store references for cleanup
    modalContent._clickHandler = clickHandler;
    modalContent._errorHandler = errorHandler;
    modalContent._loadHandler = loadHandler;
}

// Close modal
function closeModal() {
    const productModal = document.getElementById('productModal');
    if (productModal) {
        productModal.style.display = 'none';
    }

    // Remove product parameter from URL
    removeURLParameter('product');
}

// ============================================================================
// SHOPPING CART - NOT IMPLEMENTED
// Site uses inquiry-based ordering via "Request Quote" button
// ============================================================================

// Recently viewed
function addToRecentlyViewed(product) {
    // Remove if already exists
    recentlyViewed = recentlyViewed.filter(p => p.id !== product.id);
    
    // Add to beginning
    recentlyViewed.unshift(product);
    
    // Keep only last 5
    recentlyViewed = recentlyViewed.slice(0, 5);
    
    // Save and update UI
    saveRecentlyViewed();
    updateRecentlyViewedUI();
}

function saveRecentlyViewed() {
    try {
        localStorage.setItem('laonlink_recently_viewed', JSON.stringify(recentlyViewed));
    } catch (error) {
        console.warn('Failed to save recently viewed items:', error);
        // localStorage might be full or disabled - continue without saving
    }
}

function loadRecentlyViewed() {
    try {
        const saved = localStorage.getItem('laonlink_recently_viewed');
        if (saved) {
            recentlyViewed = JSON.parse(saved);
            updateRecentlyViewedUI();
        }
    } catch (error) {
        console.warn('Failed to load recently viewed items:', error);
        // Continue with empty recently viewed list
        recentlyViewed = [];
    }
}

function updateRecentlyViewedUI() {
    const container = document.getElementById('recentlyViewed');

    if (!container) {
        console.warn('Recently viewed container not found');
        return;
    }

    if (!recentlyViewed || recentlyViewed.length === 0) {
        container.innerHTML = '<p class="empty-message">No items viewed yet</p>';
    } else {
        let html = '<div style="font-size: 12px;" data-recently-viewed-list>';
        recentlyViewed.forEach(product => {
            if (!product) return;

            const productName = (product.name_en || product.name_kr || 'Unknown Product').substring(0, 30);
            const productPrice = product.price_eur_markup > 0 ? product.price_eur_markup.toFixed(2) : 'N/A';
            const productId = product.id || '';

            html += `
                <div style="margin-bottom: 10px; cursor: pointer;" data-action="view-recent" data-product-id="${productId}">
                    <div style="font-weight: bold;">${productName}...</div>
                    <div style="color: var(--primary-blue);">€${productPrice}</div>
                </div>
            `;
        });
        html += '</div>';
        container.innerHTML = html;

        // Add event delegation for recently viewed items
        if (!container._recentlyViewedHandler) {
            const handler = function(e) {
                const item = e.target.closest('[data-action="view-recent"]');
                if (item) {
                    const productId = item.dataset.productId;
                    if (productId) {
                        showProductModal(productId);
                    }
                }
            };
            container.addEventListener('click', handler);
            container._recentlyViewedHandler = handler;
        }
    }
}

// Contact for product
function contactForProduct(productId) {
    // Use Map for O(1) lookup
    const product = productMap.get(productId);
    if (!product) {
        console.error('Product not found for inquiry:', productId);
        showNotification('Product not found');
        return;
    }

    const productName = product.name_en || product.name_kr || 'Unknown Product';
    const modelNumber = product.model_number || 'N/A';

    const subject = encodeURIComponent(`Inquiry about ${productName} (ID: ${product.id})`);
    const body = encodeURIComponent(`Hello,\n\nI am interested in the following product:\n\nProduct: ${productName}\nModel: ${modelNumber}\nProduct ID: ${product.id}\n\nPlease provide more information.\n\nThank you.`);

    try {
        window.location.href = `mailto:peter.ju@laonlink.com?subject=${subject}&body=${body}`;
    } catch (error) {
        console.error('Error opening email client:', error);
        showNotification('Unable to open email client. Please contact peter.ju@laonlink.com directly.');
    }
}

// Show notification
function showNotification(message) {
    const notification = document.getElementById('notification');
    notification.textContent = message;
    notification.style.display = 'block';
    
    setTimeout(() => {
        notification.style.display = 'none';
    }, 3000);
}

// Pagination
function updatePagination() {
    const pagination = document.getElementById('pagination');
    const totalPages = Math.ceil(filteredProducts.length / productsPerPage);
    
    if (totalPages <= 1) {
        pagination.innerHTML = '';
        return;
    }
    
    let html = '';
    
    // Previous button
    html += `<button onclick="goToPage(${currentPage - 1})" ${currentPage === 1 ? 'disabled' : ''}>
        <i class="fas fa-chevron-left"></i>
    </button>`;
    
    // Page numbers
    let startPage = Math.max(1, currentPage - 2);
    let endPage = Math.min(totalPages, startPage + 4);
    
    if (startPage > 1) {
        html += `<button onclick="goToPage(1)">1</button>`;
        if (startPage > 2) html += `<button disabled>...</button>`;
    }
    
    for (let i = startPage; i <= endPage; i++) {
        html += `<button onclick="goToPage(${i})" class="${i === currentPage ? 'active' : ''}">${i}</button>`;
    }
    
    if (endPage < totalPages) {
        if (endPage < totalPages - 1) html += `<button disabled>...</button>`;
        html += `<button onclick="goToPage(${totalPages})">${totalPages}</button>`;
    }
    
    // Next button
    html += `<button onclick="goToPage(${currentPage + 1})" ${currentPage === totalPages ? 'disabled' : ''}>
        <i class="fas fa-chevron-right"></i>
    </button>`;
    
    pagination.innerHTML = html;
}

function goToPage(page) {
    const totalPages = Math.ceil(filteredProducts.length / productsPerPage);
    if (page < 1 || page > totalPages) return;

    currentPage = page;
    displayProducts();

    // Scroll to top of products
    const productArea = document.querySelector('.product-area');
    if (productArea) {
        productArea.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
}

// Back to top button
function setupBackToTop() {
    const backToTopBtn = document.getElementById('backToTop');

    if (!backToTopBtn) {
        console.warn('Back to top button not found');
        return;
    }

    window.addEventListener('scroll', function() {
        if (window.pageYOffset > 300) {
            backToTopBtn.classList.add('show');
        } else {
            backToTopBtn.classList.remove('show');
        }
    });

    backToTopBtn.addEventListener('click', function() {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    });
}

// Export functions to window only if needed for backwards compatibility
// These are now primarily handled through event delegation
if (typeof window !== 'undefined') {
    // Keep minimal global exposure for potential external use
    window.laonlink = {
        showProductModal,
        goToPage,
        showNotification
    };
}
